import {
  getFallbackSeedLogos,
  getFallbackSeedStats,
  getFallbackSeedStories,
} from "@/data/homepage-fallback";
import { getFallbackSeedTeam } from "@/data/team-fallback";
import type { CmsLogoRow, CmsStatRow, CmsStoryRow, CmsTeamMemberRow } from "@/lib/cms-types";

export let mockStats: CmsStatRow[] = getFallbackSeedStats().map((s, i) => ({
  id: i + 1,
  ...s,
  prefix: s.prefix ?? undefined,
  sortOrder: i,
  status: "published" as const,
  livePayload: {
    slug: s.slug,
    iconKey: s.iconKey,
    numValue: s.numValue,
    prefix: s.prefix ?? undefined,
    suffixEn: s.suffixEn,
    suffixHi: s.suffixHi,
    labelEn: s.labelEn,
    labelHi: s.labelHi,
  },
  publishedAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  hasUnpublishedChanges: false,
}));

export let mockLogos: CmsLogoRow[] = getFallbackSeedLogos().map((l, i) => ({
  id: i + 1,
  name: l.name,
  group: l.group,
  imageUrl: l.imageUrl,
  sortOrder: l.sortOrder,
  status: "published" as const,
  livePayload: { name: l.name, group: l.group, imageUrl: l.imageUrl },
  publishedAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  hasUnpublishedChanges: false,
}));

export let mockStories: CmsStoryRow[] = getFallbackSeedStories().map((s, i) => ({
  id: i + 1,
  ...s,
  sortOrder: i,
  status: "published" as const,
  livePayload: {
    slug: s.slug,
    nameEn: s.nameEn,
    nameHi: s.nameHi,
    roleEn: s.roleEn,
    roleHi: s.roleHi,
    locationEn: s.locationEn,
    locationHi: s.locationHi,
    acresEn: s.acresEn,
    acresHi: s.acresHi,
    cropEn: s.cropEn,
    cropHi: s.cropHi,
    quoteEn: s.quoteEn,
    quoteHi: s.quoteHi,
    badgeEn: s.badgeEn,
    badgeHi: s.badgeHi,
  publishedAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  hasUnpublishedChanges: false,
}));

export let mockTeam: CmsTeamMemberRow[] = getFallbackSeedTeam().map((m, i) => ({
  id: i + 1,
  slug: m.slug,
  nameEn: m.nameEn,
  nameHi: m.nameHi,
  roleEn: m.roleEn,
  roleHi: m.roleHi,
  focusEn: m.focusEn,
  focusHi: m.focusHi,
  tagEn: m.tagEn,
  tagHi: m.tagHi,
  bioEn: m.bioEn,
  bioHi: m.bioHi,
  quoteEn: m.quoteEn,
  quoteHi: m.quoteHi,
  pubEn: m.pubEn,
  pubHi: m.pubHi,
  keyAchEn: m.keyAchEn,
  keyAchHi: m.keyAchHi,
  imageUrl: m.imageUrl,
  iconKey: m.iconKey,
  showInBanner: m.showInBanner,
  bannerBadgeEn: m.bannerBadgeEn,
  bannerBadgeHi: m.bannerBadgeHi,
  sortOrder: m.sortOrder,
  status: "published" as const,
  livePayload: {
    slug: m.slug,
    nameEn: m.nameEn,
    nameHi: m.nameHi,
    roleEn: m.roleEn,
    roleHi: m.roleHi,
    focusEn: m.focusEn,
    focusHi: m.focusHi,
    tagEn: m.tagEn,
    tagHi: m.tagHi,
    bioEn: m.bioEn,
    bioHi: m.bioHi,
    quoteEn: m.quoteEn,
    quoteHi: m.quoteHi,
    pubEn: m.pubEn,
    pubHi: m.pubHi,
    keyAchEn: m.keyAchEn,
    keyAchHi: m.keyAchHi,
    imageUrl: m.imageUrl,
    iconKey: m.iconKey,
    showInBanner: m.showInBanner,
    bannerBadgeEn: m.bannerBadgeEn,
    bannerBadgeHi: m.bannerBadgeHi,
  },
  publishedAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  hasUnpublishedChanges: false,
}));
