/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as AgaateAdminRouteRouteImport } from './routes/agaate-admin/route'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125TermsOfServiceRouteImport } from './routes/{-$locale}/terms-of-service'
import { Route as Char123LocaleChar125PrivacyPolicyRouteImport } from './routes/{-$locale}/privacy-policy'
import { Route as Char123LocaleChar125KisaanMallRouteImport } from './routes/{-$locale}/kisaan-mall'
import { Route as Char123LocaleChar125CookiePolicyRouteImport } from './routes/{-$locale}/cookie-policy'
import { Route as Char123LocaleChar125ContactRouteImport } from './routes/{-$locale}/contact'
import { Route as Char123LocaleChar125CommunityRouteImport } from './routes/{-$locale}/community'
import { Route as Char123LocaleChar125CareersRouteImport } from './routes/{-$locale}/careers'
import { Route as Char123LocaleChar125AgriParkRouteImport } from './routes/{-$locale}/agri-park'
import { Route as Char123LocaleChar125AboutRouteImport } from './routes/{-$locale}/about'
import { Route as AgaateAdminLoginRouteImport } from './routes/agaate-admin/login'
import { Route as AgaateAdminAuthedRouteRouteImport } from './routes/agaate-admin/_authed/route'
import { Route as AgaateAdminAuthedIndexRouteImport } from './routes/agaate-admin/_authed/index'
import { Route as AgaateAdminAuthedSettingsRouteImport } from './routes/agaate-admin/_authed/settings'
import { Route as AgaateAdminAuthedFarmVisitsRouteImport } from './routes/agaate-admin/_authed/farm-visits'
import { Route as AgaateAdminAuthedContentIndexRouteImport } from './routes/agaate-admin/_authed/content/index'
import { Route as AgaateAdminAuthedContentTeamRouteImport } from './routes/agaate-admin/_authed/content/team'
import { Route as AgaateAdminAuthedContentStoriesRouteImport } from './routes/agaate-admin/_authed/content/stories'
import { Route as AgaateAdminAuthedContentStatsRouteImport } from './routes/agaate-admin/_authed/content/stats'
import { Route as AgaateAdminAuthedContentLogosRouteImport } from './routes/agaate-admin/_authed/content/logos'
import { Route as AgaateAdminAuthedContentAppLinksRouteImport } from './routes/agaate-admin/_authed/content/app-links'
import { Route as AgaateAdminAuthedContentAgriParkTourRouteImport } from './routes/agaate-admin/_authed/content/agri-park-tour'

const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgaateAdminRouteRoute = AgaateAdminRouteRouteImport.update({
  id: '/agaate-admin',
  path: '/agaate-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125TermsOfServiceRoute =
  Char123LocaleChar125TermsOfServiceRouteImport.update({
    id: '/terms-of-service',
    path: '/terms-of-service',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125PrivacyPolicyRoute =
  Char123LocaleChar125PrivacyPolicyRouteImport.update({
    id: '/privacy-policy',
    path: '/privacy-policy',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125KisaanMallRoute =
  Char123LocaleChar125KisaanMallRouteImport.update({
    id: '/kisaan-mall',
    path: '/kisaan-mall',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125CookiePolicyRoute =
  Char123LocaleChar125CookiePolicyRouteImport.update({
    id: '/cookie-policy',
    path: '/cookie-policy',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ContactRoute =
  Char123LocaleChar125ContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125CommunityRoute =
  Char123LocaleChar125CommunityRouteImport.update({
    id: '/community',
    path: '/community',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125CareersRoute =
  Char123LocaleChar125CareersRouteImport.update({
    id: '/careers',
    path: '/careers',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AgriParkRoute =
  Char123LocaleChar125AgriParkRouteImport.update({
    id: '/agri-park',
    path: '/agri-park',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AboutRoute =
  Char123LocaleChar125AboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const AgaateAdminLoginRoute = AgaateAdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AgaateAdminRouteRoute,
} as any)
const AgaateAdminAuthedRouteRoute = AgaateAdminAuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => AgaateAdminRouteRoute,
} as any)
const AgaateAdminAuthedIndexRoute = AgaateAdminAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgaateAdminAuthedRouteRoute,
} as any)
const AgaateAdminAuthedSettingsRoute =
  AgaateAdminAuthedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AgaateAdminAuthedRouteRoute,
  } as any)
const AgaateAdminAuthedFarmVisitsRoute =
  AgaateAdminAuthedFarmVisitsRouteImport.update({
    id: '/farm-visits',
    path: '/farm-visits',
    getParentRoute: () => AgaateAdminAuthedRouteRoute,
  } as any)
const AgaateAdminAuthedContentIndexRoute =
  AgaateAdminAuthedContentIndexRouteImport.update({
    id: '/content/',
    path: '/content/',
    getParentRoute: () => AgaateAdminAuthedRouteRoute,
  } as any)
const AgaateAdminAuthedContentTeamRoute =
  AgaateAdminAuthedContentTeamRouteImport.update({
    id: '/content/team',
    path: '/content/team',
    getParentRoute: () => AgaateAdminAuthedRouteRoute,
  } as any)
const AgaateAdminAuthedContentStoriesRoute =
  AgaateAdminAuthedContentStoriesRouteImport.update({
    id: '/content/stories',
    path: '/content/stories',
    getParentRoute: () => AgaateAdminAuthedRouteRoute,
  } as any)
const AgaateAdminAuthedContentStatsRoute =
  AgaateAdminAuthedContentStatsRouteImport.update({
    id: '/content/stats',
    path: '/content/stats',
    getParentRoute: () => AgaateAdminAuthedRouteRoute,
  } as any)
const AgaateAdminAuthedContentLogosRoute =
  AgaateAdminAuthedContentLogosRouteImport.update({
    id: '/content/logos',
    path: '/content/logos',
    getParentRoute: () => AgaateAdminAuthedRouteRoute,
  } as any)
const AgaateAdminAuthedContentAppLinksRoute =
  AgaateAdminAuthedContentAppLinksRouteImport.update({
    id: '/content/app-links',
    path: '/content/app-links',
    getParentRoute: () => AgaateAdminAuthedRouteRoute,
  } as any)
const AgaateAdminAuthedContentAgriParkTourRoute =
  AgaateAdminAuthedContentAgriParkTourRouteImport.update({
    id: '/content/agri-park-tour',
    path: '/content/agri-park-tour',
    getParentRoute: () => AgaateAdminAuthedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/agaate-admin': typeof AgaateAdminRouteRouteWithChildren
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/agaate-admin/login': typeof AgaateAdminLoginRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/agri-park': typeof Char123LocaleChar125AgriParkRoute
  '/{-$locale}/careers': typeof Char123LocaleChar125CareersRoute
  '/{-$locale}/community': typeof Char123LocaleChar125CommunityRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/cookie-policy': typeof Char123LocaleChar125CookiePolicyRoute
  '/{-$locale}/kisaan-mall': typeof Char123LocaleChar125KisaanMallRoute
  '/{-$locale}/privacy-policy': typeof Char123LocaleChar125PrivacyPolicyRoute
  '/{-$locale}/terms-of-service': typeof Char123LocaleChar125TermsOfServiceRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/agaate-admin/farm-visits': typeof AgaateAdminAuthedFarmVisitsRoute
  '/agaate-admin/settings': typeof AgaateAdminAuthedSettingsRoute
  '/agaate-admin/': typeof AgaateAdminAuthedIndexRoute
  '/agaate-admin/content/agri-park-tour': typeof AgaateAdminAuthedContentAgriParkTourRoute
  '/agaate-admin/content/app-links': typeof AgaateAdminAuthedContentAppLinksRoute
  '/agaate-admin/content/logos': typeof AgaateAdminAuthedContentLogosRoute
  '/agaate-admin/content/stats': typeof AgaateAdminAuthedContentStatsRoute
  '/agaate-admin/content/stories': typeof AgaateAdminAuthedContentStoriesRoute
  '/agaate-admin/content/team': typeof AgaateAdminAuthedContentTeamRoute
  '/agaate-admin/content/': typeof AgaateAdminAuthedContentIndexRoute
}
export interface FileRoutesByTo {
  '/agaate-admin': typeof AgaateAdminAuthedIndexRoute
  '/agaate-admin/login': typeof AgaateAdminLoginRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/agri-park': typeof Char123LocaleChar125AgriParkRoute
  '/{-$locale}/careers': typeof Char123LocaleChar125CareersRoute
  '/{-$locale}/community': typeof Char123LocaleChar125CommunityRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/cookie-policy': typeof Char123LocaleChar125CookiePolicyRoute
  '/{-$locale}/kisaan-mall': typeof Char123LocaleChar125KisaanMallRoute
  '/{-$locale}/privacy-policy': typeof Char123LocaleChar125PrivacyPolicyRoute
  '/{-$locale}/terms-of-service': typeof Char123LocaleChar125TermsOfServiceRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/agaate-admin/farm-visits': typeof AgaateAdminAuthedFarmVisitsRoute
  '/agaate-admin/settings': typeof AgaateAdminAuthedSettingsRoute
  '/agaate-admin/content/agri-park-tour': typeof AgaateAdminAuthedContentAgriParkTourRoute
  '/agaate-admin/content/app-links': typeof AgaateAdminAuthedContentAppLinksRoute
  '/agaate-admin/content/logos': typeof AgaateAdminAuthedContentLogosRoute
  '/agaate-admin/content/stats': typeof AgaateAdminAuthedContentStatsRoute
  '/agaate-admin/content/stories': typeof AgaateAdminAuthedContentStoriesRoute
  '/agaate-admin/content/team': typeof AgaateAdminAuthedContentTeamRoute
  '/agaate-admin/content': typeof AgaateAdminAuthedContentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/agaate-admin': typeof AgaateAdminRouteRouteWithChildren
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/agaate-admin/_authed': typeof AgaateAdminAuthedRouteRouteWithChildren
  '/agaate-admin/login': typeof AgaateAdminLoginRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/agri-park': typeof Char123LocaleChar125AgriParkRoute
  '/{-$locale}/careers': typeof Char123LocaleChar125CareersRoute
  '/{-$locale}/community': typeof Char123LocaleChar125CommunityRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/cookie-policy': typeof Char123LocaleChar125CookiePolicyRoute
  '/{-$locale}/kisaan-mall': typeof Char123LocaleChar125KisaanMallRoute
  '/{-$locale}/privacy-policy': typeof Char123LocaleChar125PrivacyPolicyRoute
  '/{-$locale}/terms-of-service': typeof Char123LocaleChar125TermsOfServiceRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/agaate-admin/_authed/farm-visits': typeof AgaateAdminAuthedFarmVisitsRoute
  '/agaate-admin/_authed/settings': typeof AgaateAdminAuthedSettingsRoute
  '/agaate-admin/_authed/': typeof AgaateAdminAuthedIndexRoute
  '/agaate-admin/_authed/content/agri-park-tour': typeof AgaateAdminAuthedContentAgriParkTourRoute
  '/agaate-admin/_authed/content/app-links': typeof AgaateAdminAuthedContentAppLinksRoute
  '/agaate-admin/_authed/content/logos': typeof AgaateAdminAuthedContentLogosRoute
  '/agaate-admin/_authed/content/stats': typeof AgaateAdminAuthedContentStatsRoute
  '/agaate-admin/_authed/content/stories': typeof AgaateAdminAuthedContentStoriesRoute
  '/agaate-admin/_authed/content/team': typeof AgaateAdminAuthedContentTeamRoute
  '/agaate-admin/_authed/content/': typeof AgaateAdminAuthedContentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/agaate-admin'
    | '/{-$locale}'
    | '/agaate-admin/login'
    | '/{-$locale}/about'
    | '/{-$locale}/agri-park'
    | '/{-$locale}/careers'
    | '/{-$locale}/community'
    | '/{-$locale}/contact'
    | '/{-$locale}/cookie-policy'
    | '/{-$locale}/kisaan-mall'
    | '/{-$locale}/privacy-policy'
    | '/{-$locale}/terms-of-service'
    | '/{-$locale}/'
    | '/agaate-admin/farm-visits'
    | '/agaate-admin/settings'
    | '/agaate-admin/'
    | '/agaate-admin/content/agri-park-tour'
    | '/agaate-admin/content/app-links'
    | '/agaate-admin/content/logos'
    | '/agaate-admin/content/stats'
    | '/agaate-admin/content/stories'
    | '/agaate-admin/content/team'
    | '/agaate-admin/content/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/agaate-admin'
    | '/agaate-admin/login'
    | '/{-$locale}/about'
    | '/{-$locale}/agri-park'
    | '/{-$locale}/careers'
    | '/{-$locale}/community'
    | '/{-$locale}/contact'
    | '/{-$locale}/cookie-policy'
    | '/{-$locale}/kisaan-mall'
    | '/{-$locale}/privacy-policy'
    | '/{-$locale}/terms-of-service'
    | '/{-$locale}'
    | '/agaate-admin/farm-visits'
    | '/agaate-admin/settings'
    | '/agaate-admin/content/agri-park-tour'
    | '/agaate-admin/content/app-links'
    | '/agaate-admin/content/logos'
    | '/agaate-admin/content/stats'
    | '/agaate-admin/content/stories'
    | '/agaate-admin/content/team'
    | '/agaate-admin/content'
  id:
    | '__root__'
    | '/agaate-admin'
    | '/{-$locale}'
    | '/agaate-admin/_authed'
    | '/agaate-admin/login'
    | '/{-$locale}/about'
    | '/{-$locale}/agri-park'
    | '/{-$locale}/careers'
    | '/{-$locale}/community'
    | '/{-$locale}/contact'
    | '/{-$locale}/cookie-policy'
    | '/{-$locale}/kisaan-mall'
    | '/{-$locale}/privacy-policy'
    | '/{-$locale}/terms-of-service'
    | '/{-$locale}/'
    | '/agaate-admin/_authed/farm-visits'
    | '/agaate-admin/_authed/settings'
    | '/agaate-admin/_authed/'
    | '/agaate-admin/_authed/content/agri-park-tour'
    | '/agaate-admin/_authed/content/app-links'
    | '/agaate-admin/_authed/content/logos'
    | '/agaate-admin/_authed/content/stats'
    | '/agaate-admin/_authed/content/stories'
    | '/agaate-admin/_authed/content/team'
    | '/agaate-admin/_authed/content/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AgaateAdminRouteRoute: typeof AgaateAdminRouteRouteWithChildren
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agaate-admin': {
      id: '/agaate-admin'
      path: '/agaate-admin'
      fullPath: '/agaate-admin'
      preLoaderRoute: typeof AgaateAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/terms-of-service': {
      id: '/{-$locale}/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/{-$locale}/terms-of-service'
      preLoaderRoute: typeof Char123LocaleChar125TermsOfServiceRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/privacy-policy': {
      id: '/{-$locale}/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/{-$locale}/privacy-policy'
      preLoaderRoute: typeof Char123LocaleChar125PrivacyPolicyRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/kisaan-mall': {
      id: '/{-$locale}/kisaan-mall'
      path: '/kisaan-mall'
      fullPath: '/{-$locale}/kisaan-mall'
      preLoaderRoute: typeof Char123LocaleChar125KisaanMallRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/cookie-policy': {
      id: '/{-$locale}/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/{-$locale}/cookie-policy'
      preLoaderRoute: typeof Char123LocaleChar125CookiePolicyRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/contact': {
      id: '/{-$locale}/contact'
      path: '/contact'
      fullPath: '/{-$locale}/contact'
      preLoaderRoute: typeof Char123LocaleChar125ContactRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/community': {
      id: '/{-$locale}/community'
      path: '/community'
      fullPath: '/{-$locale}/community'
      preLoaderRoute: typeof Char123LocaleChar125CommunityRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/careers': {
      id: '/{-$locale}/careers'
      path: '/careers'
      fullPath: '/{-$locale}/careers'
      preLoaderRoute: typeof Char123LocaleChar125CareersRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/agri-park': {
      id: '/{-$locale}/agri-park'
      path: '/agri-park'
      fullPath: '/{-$locale}/agri-park'
      preLoaderRoute: typeof Char123LocaleChar125AgriParkRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/about': {
      id: '/{-$locale}/about'
      path: '/about'
      fullPath: '/{-$locale}/about'
      preLoaderRoute: typeof Char123LocaleChar125AboutRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/agaate-admin/login': {
      id: '/agaate-admin/login'
      path: '/login'
      fullPath: '/agaate-admin/login'
      preLoaderRoute: typeof AgaateAdminLoginRouteImport
      parentRoute: typeof AgaateAdminRouteRoute
    }
    '/agaate-admin/_authed': {
      id: '/agaate-admin/_authed'
      path: ''
      fullPath: '/agaate-admin'
      preLoaderRoute: typeof AgaateAdminAuthedRouteRouteImport
      parentRoute: typeof AgaateAdminRouteRoute
    }
    '/agaate-admin/_authed/': {
      id: '/agaate-admin/_authed/'
      path: '/'
      fullPath: '/agaate-admin/'
      preLoaderRoute: typeof AgaateAdminAuthedIndexRouteImport
      parentRoute: typeof AgaateAdminAuthedRouteRoute
    }
    '/agaate-admin/_authed/settings': {
      id: '/agaate-admin/_authed/settings'
      path: '/settings'
      fullPath: '/agaate-admin/settings'
      preLoaderRoute: typeof AgaateAdminAuthedSettingsRouteImport
      parentRoute: typeof AgaateAdminAuthedRouteRoute
    }
    '/agaate-admin/_authed/farm-visits': {
      id: '/agaate-admin/_authed/farm-visits'
      path: '/farm-visits'
      fullPath: '/agaate-admin/farm-visits'
      preLoaderRoute: typeof AgaateAdminAuthedFarmVisitsRouteImport
      parentRoute: typeof AgaateAdminAuthedRouteRoute
    }
    '/agaate-admin/_authed/content/': {
      id: '/agaate-admin/_authed/content/'
      path: '/content'
      fullPath: '/agaate-admin/content/'
      preLoaderRoute: typeof AgaateAdminAuthedContentIndexRouteImport
      parentRoute: typeof AgaateAdminAuthedRouteRoute
    }
    '/agaate-admin/_authed/content/team': {
      id: '/agaate-admin/_authed/content/team'
      path: '/content/team'
      fullPath: '/agaate-admin/content/team'
      preLoaderRoute: typeof AgaateAdminAuthedContentTeamRouteImport
      parentRoute: typeof AgaateAdminAuthedRouteRoute
    }
    '/agaate-admin/_authed/content/stories': {
      id: '/agaate-admin/_authed/content/stories'
      path: '/content/stories'
      fullPath: '/agaate-admin/content/stories'
      preLoaderRoute: typeof AgaateAdminAuthedContentStoriesRouteImport
      parentRoute: typeof AgaateAdminAuthedRouteRoute
    }
    '/agaate-admin/_authed/content/stats': {
      id: '/agaate-admin/_authed/content/stats'
      path: '/content/stats'
      fullPath: '/agaate-admin/content/stats'
      preLoaderRoute: typeof AgaateAdminAuthedContentStatsRouteImport
      parentRoute: typeof AgaateAdminAuthedRouteRoute
    }
    '/agaate-admin/_authed/content/logos': {
      id: '/agaate-admin/_authed/content/logos'
      path: '/content/logos'
      fullPath: '/agaate-admin/content/logos'
      preLoaderRoute: typeof AgaateAdminAuthedContentLogosRouteImport
      parentRoute: typeof AgaateAdminAuthedRouteRoute
    }
    '/agaate-admin/_authed/content/app-links': {
      id: '/agaate-admin/_authed/content/app-links'
      path: '/content/app-links'
      fullPath: '/agaate-admin/content/app-links'
      preLoaderRoute: typeof AgaateAdminAuthedContentAppLinksRouteImport
      parentRoute: typeof AgaateAdminAuthedRouteRoute
    }
    '/agaate-admin/_authed/content/agri-park-tour': {
      id: '/agaate-admin/_authed/content/agri-park-tour'
      path: '/content/agri-park-tour'
      fullPath: '/agaate-admin/content/agri-park-tour'
      preLoaderRoute: typeof AgaateAdminAuthedContentAgriParkTourRouteImport
      parentRoute: typeof AgaateAdminAuthedRouteRoute
    }
  }
}

interface AgaateAdminAuthedRouteRouteChildren {
  AgaateAdminAuthedFarmVisitsRoute: typeof AgaateAdminAuthedFarmVisitsRoute
  AgaateAdminAuthedSettingsRoute: typeof AgaateAdminAuthedSettingsRoute
  AgaateAdminAuthedIndexRoute: typeof AgaateAdminAuthedIndexRoute
  AgaateAdminAuthedContentAgriParkTourRoute: typeof AgaateAdminAuthedContentAgriParkTourRoute
  AgaateAdminAuthedContentAppLinksRoute: typeof AgaateAdminAuthedContentAppLinksRoute
  AgaateAdminAuthedContentLogosRoute: typeof AgaateAdminAuthedContentLogosRoute
  AgaateAdminAuthedContentStatsRoute: typeof AgaateAdminAuthedContentStatsRoute
  AgaateAdminAuthedContentStoriesRoute: typeof AgaateAdminAuthedContentStoriesRoute
  AgaateAdminAuthedContentTeamRoute: typeof AgaateAdminAuthedContentTeamRoute
  AgaateAdminAuthedContentIndexRoute: typeof AgaateAdminAuthedContentIndexRoute
}

const AgaateAdminAuthedRouteRouteChildren: AgaateAdminAuthedRouteRouteChildren =
  {
    AgaateAdminAuthedFarmVisitsRoute: AgaateAdminAuthedFarmVisitsRoute,
    AgaateAdminAuthedSettingsRoute: AgaateAdminAuthedSettingsRoute,
    AgaateAdminAuthedIndexRoute: AgaateAdminAuthedIndexRoute,
    AgaateAdminAuthedContentAgriParkTourRoute:
      AgaateAdminAuthedContentAgriParkTourRoute,
    AgaateAdminAuthedContentAppLinksRoute:
      AgaateAdminAuthedContentAppLinksRoute,
    AgaateAdminAuthedContentLogosRoute: AgaateAdminAuthedContentLogosRoute,
    AgaateAdminAuthedContentStatsRoute: AgaateAdminAuthedContentStatsRoute,
    AgaateAdminAuthedContentStoriesRoute: AgaateAdminAuthedContentStoriesRoute,
    AgaateAdminAuthedContentTeamRoute: AgaateAdminAuthedContentTeamRoute,
    AgaateAdminAuthedContentIndexRoute: AgaateAdminAuthedContentIndexRoute,
  }

const AgaateAdminAuthedRouteRouteWithChildren =
  AgaateAdminAuthedRouteRoute._addFileChildren(
    AgaateAdminAuthedRouteRouteChildren,
  )

interface AgaateAdminRouteRouteChildren {
  AgaateAdminAuthedRouteRoute: typeof AgaateAdminAuthedRouteRouteWithChildren
  AgaateAdminLoginRoute: typeof AgaateAdminLoginRoute
}

const AgaateAdminRouteRouteChildren: AgaateAdminRouteRouteChildren = {
  AgaateAdminAuthedRouteRoute: AgaateAdminAuthedRouteRouteWithChildren,
  AgaateAdminLoginRoute: AgaateAdminLoginRoute,
}

const AgaateAdminRouteRouteWithChildren =
  AgaateAdminRouteRoute._addFileChildren(AgaateAdminRouteRouteChildren)

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125AboutRoute: typeof Char123LocaleChar125AboutRoute
  Char123LocaleChar125AgriParkRoute: typeof Char123LocaleChar125AgriParkRoute
  Char123LocaleChar125CareersRoute: typeof Char123LocaleChar125CareersRoute
  Char123LocaleChar125CommunityRoute: typeof Char123LocaleChar125CommunityRoute
  Char123LocaleChar125ContactRoute: typeof Char123LocaleChar125ContactRoute
  Char123LocaleChar125CookiePolicyRoute: typeof Char123LocaleChar125CookiePolicyRoute
  Char123LocaleChar125KisaanMallRoute: typeof Char123LocaleChar125KisaanMallRoute
  Char123LocaleChar125PrivacyPolicyRoute: typeof Char123LocaleChar125PrivacyPolicyRoute
  Char123LocaleChar125TermsOfServiceRoute: typeof Char123LocaleChar125TermsOfServiceRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125AboutRoute: Char123LocaleChar125AboutRoute,
    Char123LocaleChar125AgriParkRoute: Char123LocaleChar125AgriParkRoute,
    Char123LocaleChar125CareersRoute: Char123LocaleChar125CareersRoute,
    Char123LocaleChar125CommunityRoute: Char123LocaleChar125CommunityRoute,
    Char123LocaleChar125ContactRoute: Char123LocaleChar125ContactRoute,
    Char123LocaleChar125CookiePolicyRoute:
      Char123LocaleChar125CookiePolicyRoute,
    Char123LocaleChar125KisaanMallRoute: Char123LocaleChar125KisaanMallRoute,
    Char123LocaleChar125PrivacyPolicyRoute:
      Char123LocaleChar125PrivacyPolicyRoute,
    Char123LocaleChar125TermsOfServiceRoute:
      Char123LocaleChar125TermsOfServiceRoute,
    Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AgaateAdminRouteRoute: AgaateAdminRouteRouteWithChildren,
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
