/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125TermsOfServiceRouteImport } from './routes/{-$locale}/terms-of-service'
import { Route as Char123LocaleChar125TechnologyRouteImport } from './routes/{-$locale}/technology'
import { Route as Char123LocaleChar125SuccessStoriesRouteImport } from './routes/{-$locale}/success-stories'
import { Route as Char123LocaleChar125PrivacyPolicyRouteImport } from './routes/{-$locale}/privacy-policy'
import { Route as Char123LocaleChar125KnowledgeCenterRouteImport } from './routes/{-$locale}/knowledge-center'
import { Route as Char123LocaleChar125FreeFarmConsultationRouteImport } from './routes/{-$locale}/free-farm-consultation'
import { Route as Char123LocaleChar125CookiePolicyRouteImport } from './routes/{-$locale}/cookie-policy'
import { Route as Char123LocaleChar125ContactRouteImport } from './routes/{-$locale}/contact'
import { Route as Char123LocaleChar125AgriParkRouteImport } from './routes/{-$locale}/agri-park'
import { Route as Char123LocaleChar125AboutRouteImport } from './routes/{-$locale}/about'
import { Route as Char123LocaleChar125ServicesIndexRouteImport } from './routes/{-$locale}/services/index'

const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125TermsOfServiceRoute =
  Char123LocaleChar125TermsOfServiceRouteImport.update({
    id: '/terms-of-service',
    path: '/terms-of-service',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125TechnologyRoute =
  Char123LocaleChar125TechnologyRouteImport.update({
    id: '/technology',
    path: '/technology',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125SuccessStoriesRoute =
  Char123LocaleChar125SuccessStoriesRouteImport.update({
    id: '/success-stories',
    path: '/success-stories',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125PrivacyPolicyRoute =
  Char123LocaleChar125PrivacyPolicyRouteImport.update({
    id: '/privacy-policy',
    path: '/privacy-policy',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125KnowledgeCenterRoute =
  Char123LocaleChar125KnowledgeCenterRouteImport.update({
    id: '/knowledge-center',
    path: '/knowledge-center',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125FreeFarmConsultationRoute =
  Char123LocaleChar125FreeFarmConsultationRouteImport.update({
    id: '/free-farm-consultation',
    path: '/free-farm-consultation',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125CookiePolicyRoute =
  Char123LocaleChar125CookiePolicyRouteImport.update({
    id: '/cookie-policy',
    path: '/cookie-policy',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ContactRoute =
  Char123LocaleChar125ContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AgriParkRoute =
  Char123LocaleChar125AgriParkRouteImport.update({
    id: '/agri-park',
    path: '/agri-park',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AboutRoute =
  Char123LocaleChar125AboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ServicesIndexRoute =
  Char123LocaleChar125ServicesIndexRouteImport.update({
    id: '/services/',
    path: '/services/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/agri-park': typeof Char123LocaleChar125AgriParkRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/cookie-policy': typeof Char123LocaleChar125CookiePolicyRoute
  '/{-$locale}/free-farm-consultation': typeof Char123LocaleChar125FreeFarmConsultationRoute
  '/{-$locale}/knowledge-center': typeof Char123LocaleChar125KnowledgeCenterRoute
  '/{-$locale}/privacy-policy': typeof Char123LocaleChar125PrivacyPolicyRoute
  '/{-$locale}/success-stories': typeof Char123LocaleChar125SuccessStoriesRoute
  '/{-$locale}/technology': typeof Char123LocaleChar125TechnologyRoute
  '/{-$locale}/terms-of-service': typeof Char123LocaleChar125TermsOfServiceRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/services/': typeof Char123LocaleChar125ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/agri-park': typeof Char123LocaleChar125AgriParkRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/cookie-policy': typeof Char123LocaleChar125CookiePolicyRoute
  '/{-$locale}/free-farm-consultation': typeof Char123LocaleChar125FreeFarmConsultationRoute
  '/{-$locale}/knowledge-center': typeof Char123LocaleChar125KnowledgeCenterRoute
  '/{-$locale}/privacy-policy': typeof Char123LocaleChar125PrivacyPolicyRoute
  '/{-$locale}/success-stories': typeof Char123LocaleChar125SuccessStoriesRoute
  '/{-$locale}/technology': typeof Char123LocaleChar125TechnologyRoute
  '/{-$locale}/terms-of-service': typeof Char123LocaleChar125TermsOfServiceRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/services': typeof Char123LocaleChar125ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/agri-park': typeof Char123LocaleChar125AgriParkRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/cookie-policy': typeof Char123LocaleChar125CookiePolicyRoute
  '/{-$locale}/free-farm-consultation': typeof Char123LocaleChar125FreeFarmConsultationRoute
  '/{-$locale}/knowledge-center': typeof Char123LocaleChar125KnowledgeCenterRoute
  '/{-$locale}/privacy-policy': typeof Char123LocaleChar125PrivacyPolicyRoute
  '/{-$locale}/success-stories': typeof Char123LocaleChar125SuccessStoriesRoute
  '/{-$locale}/technology': typeof Char123LocaleChar125TechnologyRoute
  '/{-$locale}/terms-of-service': typeof Char123LocaleChar125TermsOfServiceRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/services/': typeof Char123LocaleChar125ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/{-$locale}/about'
    | '/{-$locale}/agri-park'
    | '/{-$locale}/contact'
    | '/{-$locale}/cookie-policy'
    | '/{-$locale}/free-farm-consultation'
    | '/{-$locale}/knowledge-center'
    | '/{-$locale}/privacy-policy'
    | '/{-$locale}/success-stories'
    | '/{-$locale}/technology'
    | '/{-$locale}/terms-of-service'
    | '/{-$locale}/'
    | '/{-$locale}/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}/about'
    | '/{-$locale}/agri-park'
    | '/{-$locale}/contact'
    | '/{-$locale}/cookie-policy'
    | '/{-$locale}/free-farm-consultation'
    | '/{-$locale}/knowledge-center'
    | '/{-$locale}/privacy-policy'
    | '/{-$locale}/success-stories'
    | '/{-$locale}/technology'
    | '/{-$locale}/terms-of-service'
    | '/{-$locale}'
    | '/{-$locale}/services'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/{-$locale}/about'
    | '/{-$locale}/agri-park'
    | '/{-$locale}/contact'
    | '/{-$locale}/cookie-policy'
    | '/{-$locale}/free-farm-consultation'
    | '/{-$locale}/knowledge-center'
    | '/{-$locale}/privacy-policy'
    | '/{-$locale}/success-stories'
    | '/{-$locale}/technology'
    | '/{-$locale}/terms-of-service'
    | '/{-$locale}/'
    | '/{-$locale}/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/terms-of-service': {
      id: '/{-$locale}/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/{-$locale}/terms-of-service'
      preLoaderRoute: typeof Char123LocaleChar125TermsOfServiceRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/technology': {
      id: '/{-$locale}/technology'
      path: '/technology'
      fullPath: '/{-$locale}/technology'
      preLoaderRoute: typeof Char123LocaleChar125TechnologyRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/success-stories': {
      id: '/{-$locale}/success-stories'
      path: '/success-stories'
      fullPath: '/{-$locale}/success-stories'
      preLoaderRoute: typeof Char123LocaleChar125SuccessStoriesRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/privacy-policy': {
      id: '/{-$locale}/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/{-$locale}/privacy-policy'
      preLoaderRoute: typeof Char123LocaleChar125PrivacyPolicyRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/knowledge-center': {
      id: '/{-$locale}/knowledge-center'
      path: '/knowledge-center'
      fullPath: '/{-$locale}/knowledge-center'
      preLoaderRoute: typeof Char123LocaleChar125KnowledgeCenterRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/free-farm-consultation': {
      id: '/{-$locale}/free-farm-consultation'
      path: '/free-farm-consultation'
      fullPath: '/{-$locale}/free-farm-consultation'
      preLoaderRoute: typeof Char123LocaleChar125FreeFarmConsultationRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/cookie-policy': {
      id: '/{-$locale}/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/{-$locale}/cookie-policy'
      preLoaderRoute: typeof Char123LocaleChar125CookiePolicyRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/contact': {
      id: '/{-$locale}/contact'
      path: '/contact'
      fullPath: '/{-$locale}/contact'
      preLoaderRoute: typeof Char123LocaleChar125ContactRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/agri-park': {
      id: '/{-$locale}/agri-park'
      path: '/agri-park'
      fullPath: '/{-$locale}/agri-park'
      preLoaderRoute: typeof Char123LocaleChar125AgriParkRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/about': {
      id: '/{-$locale}/about'
      path: '/about'
      fullPath: '/{-$locale}/about'
      preLoaderRoute: typeof Char123LocaleChar125AboutRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/services/': {
      id: '/{-$locale}/services/'
      path: '/services'
      fullPath: '/{-$locale}/services/'
      preLoaderRoute: typeof Char123LocaleChar125ServicesIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
  }
}

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125AboutRoute: typeof Char123LocaleChar125AboutRoute
  Char123LocaleChar125AgriParkRoute: typeof Char123LocaleChar125AgriParkRoute
  Char123LocaleChar125ContactRoute: typeof Char123LocaleChar125ContactRoute
  Char123LocaleChar125CookiePolicyRoute: typeof Char123LocaleChar125CookiePolicyRoute
  Char123LocaleChar125FreeFarmConsultationRoute: typeof Char123LocaleChar125FreeFarmConsultationRoute
  Char123LocaleChar125KnowledgeCenterRoute: typeof Char123LocaleChar125KnowledgeCenterRoute
  Char123LocaleChar125PrivacyPolicyRoute: typeof Char123LocaleChar125PrivacyPolicyRoute
  Char123LocaleChar125SuccessStoriesRoute: typeof Char123LocaleChar125SuccessStoriesRoute
  Char123LocaleChar125TechnologyRoute: typeof Char123LocaleChar125TechnologyRoute
  Char123LocaleChar125TermsOfServiceRoute: typeof Char123LocaleChar125TermsOfServiceRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
  Char123LocaleChar125ServicesIndexRoute: typeof Char123LocaleChar125ServicesIndexRoute
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125AboutRoute: Char123LocaleChar125AboutRoute,
    Char123LocaleChar125AgriParkRoute: Char123LocaleChar125AgriParkRoute,
    Char123LocaleChar125ContactRoute: Char123LocaleChar125ContactRoute,
    Char123LocaleChar125CookiePolicyRoute:
      Char123LocaleChar125CookiePolicyRoute,
    Char123LocaleChar125FreeFarmConsultationRoute:
      Char123LocaleChar125FreeFarmConsultationRoute,
    Char123LocaleChar125KnowledgeCenterRoute:
      Char123LocaleChar125KnowledgeCenterRoute,
    Char123LocaleChar125PrivacyPolicyRoute:
      Char123LocaleChar125PrivacyPolicyRoute,
    Char123LocaleChar125SuccessStoriesRoute:
      Char123LocaleChar125SuccessStoriesRoute,
    Char123LocaleChar125TechnologyRoute: Char123LocaleChar125TechnologyRoute,
    Char123LocaleChar125TermsOfServiceRoute:
      Char123LocaleChar125TermsOfServiceRoute,
    Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
    Char123LocaleChar125ServicesIndexRoute:
      Char123LocaleChar125ServicesIndexRoute,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
