-- Optional CRM columns on existing `leads` table.
-- The app also applies these at runtime via ensureLeadCrmColumns().

ALTER TABLE leads
  ADD COLUMN IF NOT EXISTS status VARCHAR(32) NOT NULL DEFAULT 'new',
  ADD COLUMN IF NOT EXISTS priority VARCHAR(16) NOT NULL DEFAULT 'medium',
  ADD COLUMN IF NOT EXISTS assigned_to BIGINT UNSIGNED NULL,
  ADD COLUMN IF NOT EXISTS follow_up_date DATE NULL,
  ADD COLUMN IF NOT EXISTS tags JSON NULL,
  ADD COLUMN IF NOT EXISTS attachment_url VARCHAR(512) NULL,
  ADD COLUMN IF NOT EXISTS preferred_language VARCHAR(16) NULL DEFAULT 'en',
  ADD COLUMN IF NOT EXISTS company_name VARCHAR(160) NULL,
  ADD COLUMN IF NOT EXISTS website VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS farm_details JSON NULL,
  ADD COLUMN IF NOT EXISTS updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
